### PR TITLE
Updates for FLAMEGPU v2-rc1 release

### LINKED ISSUE #5: [Bug] CMake configure fails
### Is your feature request related to a problem?

While attempting to build [FLAMEGPU2-pedestrian_navigation-example](https://github.com/FLAMEGPU/FLAMEGPU2-pedestrian_navigation-example), I've encountered several problems and could not get the example to build correctly. This example is of value to my friend's research project in large-scale agent modeling, and we would like to get it to run to see if it warrants further efforts into FLAMEGPU2 and the pedestrian navigation example.

There are several problems with the existing CMake configuration and build.
- GLEW dependency isn't pulled and linked correctly. This is likely an issue with FindGLEW (or perhaps how the example template links GLEW). CMake complains that GLEW::GLEW is a non-existent target.
- Some compile flags are out of date with FLAMEGPU2: VISUALISATION -> FLAMEGPU2_VISUALISATION

Operating System: Windows 11 Pro
Version: 10.0.22621
CUDA Toolkit: 12.4
Generator: Visual Studio 17 (Visual Studio 2022)

Machine Spec: 
CPU: i9-10900K
GPU: NVIDIA RTX 4080

### Describe the solution you'd like

Add [FLAMEGPU2-pedestrian_navigation-example](https://github.com/FLAMEGPU/FLAMEGPU2-pedestrian_navigation-example) as an example in examples/cpp/

or

update [FLAMEGPU2-pedestrian_navigation-example](https://github.com/FLAMEGPU/FLAMEGPU2-pedestrian_navigation-example) so that it builds correctly on the specified operating system and toolchain.

### Describe alternatives you've considered

_No response_

### Additional context

I've composed a draft pull request that successfully produces a build on the specified operating system & toolchain. However, the application seems to be stuck in loading state (or takes a very long time to load. I gave it ~10 minutes on my machine).

### PR DESCRIPTION
**Pull request by Robadob**
image

Closes #5

### CODE REVIEW

**Comment by ptheywood** [comment]
I get 2 lines printed to stdout when running this (But I have a feeling this might have been an existing thing? / not model /2.0.0-rc1 specific?). 

```
instanced_default_Tcolor_Tpos_Tdir_Tscale-material_flat_Tcolor: Generic vertex attrib named: _normal2 was not found.
instanced_default_Tcolor_Tpos_Tdir_Tscale-material_flat_Tcolor: Generic vertex attrib named: _normal2 was not found.
```

Has been sat on this for a fair while now, and is not paused. Though it might have been CUDA >=12.2 bug (Think its 12.4) but that should have finished by now...

image

Will try a 12.0 build just incase.

**Comment by Robadob** [comment]
Same lines are shown output in my screenshot above. Afaik it's a low priority visualiser bug. Low enough priority that it doesn't have an issue in that repo. Something up with the procedurally generated shader for this model (possibly all animated models).

**Comment by ptheywood** [comment]
> Will try a 12.0 build just incase.

It's not an RTC model anyway so that's not the cause of the hang.

The changes to this repo are trivial and look fine, so must be something in flame/vis. Will try some other builds.

**Comment by Robadob** [comment]
Ah overlooked that you were stuck on splash, that's odd (especially if you're not seeing it on other models).

**Comment by ptheywood** [comment]
`circles_spatial3D` in the main repo is fine. 

For spatial, the step counter progress withouth the splash screen being cleared or any agents being rendered. I can move the camere and interact with the menus. 


Must be related to the multithreading somhow but not sure how that would be model specific, unless there is some form of race?

**Comment by ptheywood** [comment]
The current `master` of this model behaves the same for me, so it's not been caused by a PR, so if this fixes windows builds then worth merging, and can investigate linux issues later. (I'll open an issue).

**Review by ptheywood — APPROVED** [review]
Changes look sensible, fixes windows behaviour but not tested as correct on linux due to #6, which seems independent of these changes, so merging anyway.

**Comment by ptheywood** [comment]
Ignore the above comments about hangs, it's just what happens when you don't pass the map input file... (my bad)

**Pull request merged**
